title: Pao Spirit Club

url: ""

baseurl: ""

author: Sandy Wu

social_links:
  pinterest: P
  facebook: F
  twitter: T
  instagram: I

date_format: "%B %-d, %Y"

timezone: China/Shanghai

permalink: /:title

markdown: kramdown

exclude:
  - .sass_cache/
  - .jekyll_cache/
  - .gitignore
  - CNAME
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - LICENSE
  - README.md
