title: Pao Spirit Club

url: ""

baseurl: ""

author: Sandy Wu

social_links:
  pinterest: P
  facebook: F
  twitter: T
  instagram: I

date_format: "%B %-d, %Y"

timezone: China/Shanghai

permalink: /:title

markdown: kramdown

defaults:
  - scope:
      path: photos/volleyball
    values:
      field: volleyball
  - scope:
      path: photos/basketball
    values:
      field: basketball
  - scope:
      path: photos/football
    values:
      field: football
  - scope:
      path: photos/frisbee
    values:
      field: frisbee
  - scope:
      path: photos/swimming
    values:
      field: swimming

exclude:
  - .sass_cache/
  - .jekyll_cache/
  - .gitignore
  - CNAME
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - LICENSE
  - README.md
  - create_thumbnails.py
